# Generated by Django 2.0.5 on 2018-06-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180627_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Last_Name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
